// Données de démo pour les vidéos - Mode démo sans backend

export interface DemoVideo {
  id: string
  title: string
  thumbnail: string
  duration: string
  views: number
  comments: number
  athlete: string
  uploader: string
  uploadedAt: string
  weapon_type?: string
  competition_name?: string
  competition_date?: string
  category?: string
  age?: number
  club?: string
  department?: string
  region?: string
}

export const DEMO_VIDEOS: DemoVideo[] = [
  {
    id: "1",
    title: "Championnat de France U15 - Finale",
    thumbnail: "https://placehold.co/400x225?text=Championnat+U15",
    duration: "05:32",
    views: 1247,
    comments: 23,
    athlete: "Lucas Martin",
    uploader: "Contact Local",
    uploadedAt: "il y a 2 jours",
    weapon_type: "epee",
    competition_name: "Championnat de France U15",
    competition_date: "2025-01-13",
    category: "U15",
    age: 14,
    club: "Cercle d'Escrime de Paris",
    department: "75",
    region: "Île-de-France",
  },
  {
    id: "2",
    title: "Tournoi Régional Île-de-France - Demi-finale",
    thumbnail: "https://placehold.co/400x225?text=Tournoi+Regional",
    duration: "04:18",
    views: 892,
    comments: 15,
    athlete: "Emma Dubois",
    uploader: "Coach Principal",
    uploadedAt: "il y a 3 jours",
    weapon_type: "foil",
    competition_name: "Tournoi Régional Île-de-France",
    competition_date: "2025-01-12",
    category: "U17",
    age: 16,
    club: "AS Escrime Lyon",
    department: "69",
    region: "Auvergne-Rhône-Alpes",
  },
  {
    id: "3",
    title: "Coupe de France Cadets - Quart de finale",
    thumbnail: "https://placehold.co/400x225?text=Coupe+Cadets",
    duration: "06:45",
    views: 2156,
    comments: 42,
    athlete: "Thomas Bernard",
    uploader: "Contact Local",
    uploadedAt: "il y a 4 jours",
    weapon_type: "sabre",
    competition_name: "Coupe de France Cadets",
    competition_date: "2025-01-11",
    category: "U20",
    age: 18,
    club: "Cercle d'Escrime Marseille",
    department: "13",
    region: "Provence-Alpes-Côte d'Azur",
  },
  {
    id: "4",
    title: "Championnat Régional PACA - Finale",
    thumbnail: "https://placehold.co/400x225?text=Championnat+PACA",
    duration: "05:12",
    views: 678,
    comments: 12,
    athlete: "Sophie Laurent",
    uploader: "Coach Principal",
    uploadedAt: "il y a 5 jours",
    weapon_type: "epee",
    competition_name: "Championnat Régional PACA",
    competition_date: "2025-01-10",
    category: "U15",
    age: 14,
    club: "Club Escrime Nice",
    department: "06",
    region: "Provence-Alpes-Côte d'Azur",
  },
  {
    id: "5",
    title: "Tournoi National U17 - Huitième de finale",
    thumbnail: "https://placehold.co/400x225?text=Tournoi+National",
    duration: "04:56",
    views: 1345,
    comments: 28,
    athlete: "Hugo Moreau",
    uploader: "Contact Local",
    uploadedAt: "il y a 6 jours",
    weapon_type: "foil",
    competition_name: "Tournoi National U17",
    competition_date: "2025-01-09",
    category: "U17",
    age: 16,
    club: "Cercle d'Escrime Bordeaux",
    department: "33",
    region: "Nouvelle-Aquitaine",
  },
  {
    id: "6",
    title: "Championnat de France U20 - Demi-finale",
    thumbnail: "https://placehold.co/400x225?text=Championnat+U20",
    duration: "07:23",
    views: 1890,
    comments: 35,
    athlete: "Léa Petit",
    uploader: "Coach Principal",
    uploadedAt: "il y a 1 semaine",
    weapon_type: "sabre",
    competition_name: "Championnat de France U20",
    competition_date: "2025-01-08",
    category: "U20",
    age: 19,
    club: "AS Escrime Toulouse",
    department: "31",
    region: "Occitanie",
  },
  {
    id: "7",
    title: "Lucas Martin vs Adversaire - Match amical",
    thumbnail: "https://placehold.co/400x225?text=Match+Amical",
    duration: "08:15",
    views: 456,
    comments: 8,
    athlete: "Lucas Martin vs Adversaire",
    uploader: "Contact Local",
    uploadedAt: "il y a 1 semaine",
    weapon_type: "epee",
    competition_name: "Match amical",
    competition_date: "2025-01-07",
    category: "U15",
    age: 14,
    club: "Cercle d'Escrime de Paris",
    department: "75",
    region: "Île-de-France",
  },
  {
    id: "8",
    title: "Emma Dubois - Entraînement technique",
    thumbnail: "https://placehold.co/400x225?text=Entrainement",
    duration: "12:34",
    views: 723,
    comments: 19,
    athlete: "Emma Dubois",
    uploader: "Coach Principal",
    uploadedAt: "il y a 2 semaines",
    weapon_type: "foil",
    competition_name: "Entraînement",
    competition_date: "2025-01-05",
    category: "U17",
    age: 16,
    club: "AS Escrime Lyon",
    department: "69",
    region: "Auvergne-Rhône-Alpes",
  },
]

