// Données de démo pour les athlètes - Mode démo sans backend

export interface DemoAthlete {
  id: string
  first_name: string
  last_name: string
  date_of_birth: string
  gender: "male" | "female"
  weapon: "foil" | "sabre" | "epee" | "épée"
  skill_level: "beginner" | "intermediate" | "advanced" | "elite"
  avatar_url?: string
  videos_count: number
  region: string
  club: string
  coach?: string
  ranking?: string
  recent_activity?: string
}

export const DEMO_ATHLETES: DemoAthlete[] = [
  {
    id: "1",
    first_name: "Lucas",
    last_name: "Martin",
    date_of_birth: "2010-05-15",
    gender: "male",
    weapon: "epee",
    skill_level: "advanced",
    avatar_url: "https://placehold.co/200x200?text=LM",
    videos_count: 12,
    region: "Île-de-France",
    club: "Cercle d'Escrime de Paris",
    coach: "Jean Dupont",
    ranking: "#15 U15",
    recent_activity: "Championnat de France U15",
  },
  {
    id: "2",
    first_name: "Emma",
    last_name: "Dubois",
    date_of_birth: "2008-08-22",
    gender: "female",
    weapon: "foil",
    skill_level: "elite",
    avatar_url: "https://placehold.co/200x200?text=ED",
    videos_count: 18,
    region: "Auvergne-Rhône-Alpes",
    club: "AS Escrime Lyon",
    coach: "Marie Laurent",
    ranking: "#3 U17",
    recent_activity: "Tournoi Régional Île-de-France",
  },
  {
    id: "3",
    first_name: "Thomas",
    last_name: "Bernard",
    date_of_birth: "2006-03-10",
    gender: "male",
    weapon: "sabre",
    skill_level: "advanced",
    avatar_url: "https://placehold.co/200x200?text=TB",
    videos_count: 15,
    region: "Provence-Alpes-Côte d'Azur",
    club: "Cercle d'Escrime Marseille",
    coach: "Pierre Moreau",
    ranking: "#8 U20",
    recent_activity: "Coupe de France Cadets",
  },
  {
    id: "4",
    first_name: "Sophie",
    last_name: "Laurent",
    date_of_birth: "2010-11-05",
    gender: "female",
    weapon: "epee",
    skill_level: "intermediate",
    avatar_url: "https://placehold.co/200x200?text=SL",
    videos_count: 8,
    region: "Provence-Alpes-Côte d'Azur",
    club: "Club Escrime Nice",
    coach: "Claire Petit",
    ranking: "#22 U15",
    recent_activity: "Championnat Régional PACA",
  },
  {
    id: "5",
    first_name: "Hugo",
    last_name: "Moreau",
    date_of_birth: "2008-07-18",
    gender: "male",
    weapon: "foil",
    skill_level: "advanced",
    avatar_url: "https://placehold.co/200x200?text=HM",
    videos_count: 14,
    region: "Nouvelle-Aquitaine",
    club: "Cercle d'Escrime Bordeaux",
    coach: "Antoine Martin",
    ranking: "#12 U17",
    recent_activity: "Tournoi National U17",
  },
  {
    id: "6",
    first_name: "Léa",
    last_name: "Petit",
    date_of_birth: "2005-12-03",
    gender: "female",
    weapon: "sabre",
    skill_level: "elite",
    avatar_url: "https://placehold.co/200x200?text=LP",
    videos_count: 20,
    region: "Occitanie",
    club: "AS Escrime Toulouse",
    coach: "Sophie Bernard",
    ranking: "#2 U20",
    recent_activity: "Championnat de France U20",
  },
  {
    id: "7",
    first_name: "Alexandre",
    last_name: "Garcia",
    date_of_birth: "2011-02-14",
    gender: "male",
    weapon: "foil",
    skill_level: "beginner",
    avatar_url: "https://placehold.co/200x200?text=AG",
    videos_count: 3,
    region: "Île-de-France",
    club: "Cercle d'Escrime de Paris",
    coach: "Jean Dupont",
    ranking: "-",
    recent_activity: "Entraînement",
  },
  {
    id: "8",
    first_name: "Camille",
    last_name: "Rousseau",
    date_of_birth: "2009-09-25",
    gender: "female",
    weapon: "epee",
    skill_level: "intermediate",
    avatar_url: "https://placehold.co/200x200?text=CR",
    videos_count: 7,
    region: "Auvergne-Rhône-Alpes",
    club: "AS Escrime Lyon",
    coach: "Marie Laurent",
    ranking: "#28 U15",
    recent_activity: "Compétition locale",
  },
  {
    id: "9",
    first_name: "Maxime",
    last_name: "Lefebvre",
    date_of_birth: "2007-04-30",
    gender: "male",
    weapon: "sabre",
    skill_level: "advanced",
    avatar_url: "https://placehold.co/200x200?text=ML",
    videos_count: 11,
    region: "Hauts-de-France",
    club: "Club Escrime Lille",
    coach: "Paul Durand",
    ranking: "#18 U17",
    recent_activity: "Tournoi régional",
  },
  {
    id: "10",
    first_name: "Julie",
    last_name: "Simon",
    date_of_birth: "2010-06-12",
    gender: "female",
    weapon: "foil",
    skill_level: "intermediate",
    avatar_url: "https://placehold.co/200x200?text=JS",
    videos_count: 6,
    region: "Grand Est",
    club: "Cercle d'Escrime Strasbourg",
    coach: "Anne Muller",
    ranking: "#35 U15",
    recent_activity: "Match amical",
  },
  {
    id: "11",
    first_name: "Nicolas",
    last_name: "Fournier",
    date_of_birth: "2008-10-08",
    gender: "male",
    weapon: "epee",
    skill_level: "advanced",
    avatar_url: "https://placehold.co/200x200?text=NF",
    videos_count: 13,
    region: "Nouvelle-Aquitaine",
    club: "Cercle d'Escrime Bordeaux",
    coach: "Antoine Martin",
    ranking: "#14 U17",
    recent_activity: "Championnat régional",
  },
  {
    id: "12",
    first_name: "Manon",
    last_name: "Girard",
    date_of_birth: "2006-01-20",
    gender: "female",
    weapon: "sabre",
    skill_level: "elite",
    avatar_url: "https://placehold.co/200x200?text=MG",
    videos_count: 19,
    region: "Provence-Alpes-Côte d'Azur",
    club: "Cercle d'Escrime Marseille",
    coach: "Pierre Moreau",
    ranking: "#5 U20",
    recent_activity: "Coupe de France",
  },
]

